// ===============================
// useDemoChatBot.js - 깨끗한 새 버전
// src/components/ui/ChatBot/hooks/useDemoChatBot.js
// ===============================

import { useState, useCallback, useRef, useEffect } from 'react';
import { processCategories, processIssues, expertCategories, getCurrentIssue } from '../data/chatBotDemoData';

// API 호출 함수
const callApi = async (endpoint, payload) => {
  try {
    const response = await fetch(`http://localhost:8000${endpoint}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload)
    });
    
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    
    return await response.json();
  } catch (error) {
    console.error('API 호출 실패:', error);
    throw error;
  }
};

export const useDemoChatBot = () => {
  // 기본 상태
  const [isOpen, setIsOpen] = useState(false);
  const [currentStep, setCurrentStep] = useState('process'); // process → issue → expert → chat
  const [selectedProcess, setSelectedProcess] = useState(null);
  const [selectedIssue, setSelectedIssue] = useState(null);
  const [selectedExpert, setSelectedExpert] = useState(null);
  const [sessionId, setSessionId] = useState(null);
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  
  // 시연 관련 상태
  const [demoStep, setDemoStep] = useState(1);
  const [apiConnected, setApiConnected] = useState(true);
  const [lastError, setLastError] = useState(null);
  const [typingEffect, setTypingEffect] = useState(false);
  
  // refs
  const isComponentMountedRef = useRef(true);
  const messagesEndRef = useRef(null);

  // 컴포넌트 정리
  useEffect(() => {
    return () => {
      isComponentMountedRef.current = false;
    };
  }, []);

  // 메시지 변경 시 자동 스크롤
  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading, typingEffect]);

  // 자동 스크롤 함수
  const scrollToBottom = () => {
    setTimeout(() => {
      messagesEndRef.current?.scrollIntoView({ 
        behavior: 'smooth',
        block: 'end'
      });
    }, 100);
  };

  // 안전한 상태 업데이트
  const safeSetState = useCallback((setter) => {
    if (isComponentMountedRef.current) {
      setter();
    }
  }, []);

  // 챗봇 토글
  const toggleChat = useCallback(() => {
    setIsOpen(prev => !prev);
  }, []);

  // 리셋
  const resetChat = useCallback(() => {
    safeSetState(() => {
      setCurrentStep('process');
      setSelectedProcess(null);
      setSelectedIssue(null);
      setSelectedExpert(null);
      setSessionId(null);
      setMessages([]);
      setInputValue('');
      setIsLoading(false);
      setDemoStep(1);
      setLastError(null);
      setTypingEffect(false);
    });
  }, [safeSetState]);

  // 1단계: 공정 선택
  const handleProcessSelect = useCallback((process) => {
    setSelectedProcess(process);
    setCurrentStep('issue');
  }, []);

  // 2단계: 이슈 선택
  const handleIssueSelect = useCallback((issue) => {
    setSelectedIssue(issue);
    setCurrentStep('expert');
  }, []);

  // 3단계: 전문가 선택 및 상담 시작
  const handleExpertSelect = useCallback(async (expert) => {
    if (!selectedIssue) return;
    
    setIsLoading(true);
    setLastError(null);
    
    try {
      // 세션 생성
      const sessionResponse = await callApi('/api/session/new', {});
      const newSessionId = sessionResponse.session_id || `session_${Date.now()}`;
      
      setSelectedExpert(expert);
      setSessionId(newSessionId);
      setCurrentStep('chat');
      
      const stepMap = {
        'multi-agent': 1,
        'safety': 2,
        'technical': 3
      };
      setDemoStep(stepMap[expert.id] || 1);
      
      // 현재 이슈 정보 가져오기
      const currentIssue = getCurrentIssue(selectedIssue.id);
      
      // 환영 메시지
      const welcomeMessage = {
        id: Date.now(),
        text: `안녕하세요! ${expert.name} 전문가입니다.\n\n현재 감지된 이슈: **${currentIssue.name}**\n위치: ${currentIssue.location}\n심각도: ${currentIssue.severity}\n상태: ${currentIssue.urgency}\n\n이 문제에 대해 상세한 분석과 해결 방안을 제공해드리겠습니다.`,
        isUser: false,
        timestamp: new Date(),
        isWelcome: true
      };
      
      setMessages([welcomeMessage]);
      
      // 자동 질문 실행 (인라인 함수로 의존성 제거)
      setTimeout(async () => {
        setTypingEffect(true);
        
        // 사용자 질문
        const userMessage = {
          id: Date.now(),
          text: getQuestionText(expert.id, currentIssue),
          isUser: true,
          timestamp: new Date(),
          isAutoGenerated: true
        };
        
        setMessages(prev => [...prev, userMessage]);
        
        try {
          // API 호출
          const endpoint = getApiEndpoint(expert.id);
          const payload = getApiPayload(expert.id, newSessionId, userMessage.text, currentIssue.id);
          
          const response = await callApi(endpoint, payload);
          
          // 봇 응답
          const botMessage = {
            id: Date.now() + 1,
            text: formatResponse(response, expert.id),
            isUser: false,
            timestamp: new Date(),
            metadata: response
          };
          
          setMessages(prev => [...prev, botMessage]);
          
        } catch (error) {
          const errorMessage = {
            id: Date.now() + 1,
            text: `❌ ${expert.name} 분석 중 오류가 발생했습니다. 다시 시도해주세요.`,
            isUser: false,
            timestamp: new Date(),
            isError: true
          };
          setMessages(prev => [...prev, errorMessage]);
        } finally {
          setTypingEffect(false);
        }
      }, 2000);
      
    } catch (error) {
      setLastError({
        type: 'CONNECTION_ERROR',
        message: 'AI 서비스 연결에 실패했습니다.',
        isRetryable: true
      });
    } finally {
      setIsLoading(false);
    }
  }, [selectedIssue]);

  // 자동 질문 함수 제거 (위에서 인라인으로 처리)

  // 수동 메시지 전송
  const handleSendMessage = useCallback(async () => {
    const trimmedInput = inputValue.trim();
    if (!trimmedInput || isLoading || !sessionId || !selectedExpert || !selectedIssue) return;
    
    const userMessage = {
      id: Date.now(),
      text: trimmedInput,
      isUser: true,
      timestamp: new Date()
    };
    
    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsLoading(true);
    
    try {
      const endpoint = getApiEndpoint(selectedExpert.id);
      const payload = getApiPayload(selectedExpert.id, sessionId, trimmedInput, selectedIssue.id);
      const response = await callApi(endpoint, payload);
      
      const botMessage = {
        id: Date.now() + 1,
        text: formatResponse(response, selectedExpert.id),
        isUser: false,
        timestamp: new Date()
      };
      
      setMessages(prev => [...prev, botMessage]);
      
    } catch (error) {
      const errorMessage = {
        id: Date.now() + 1,
        text: '❌ 메시지 처리 중 오류가 발생했습니다.',
        isUser: false,
        timestamp: new Date(),
        isError: true
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  }, [inputValue, sessionId, selectedExpert, selectedIssue, isLoading]);

  // 키보드 이벤트
  const handleKeyPress = useCallback((e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  }, [handleSendMessage]);

  const handleInputChange = useCallback((e) => {
    setInputValue(e.target.value);
  }, []);

  // 뒤로 가기
  const handleBack = useCallback(() => {
    if (currentStep === 'issue') {
      setCurrentStep('process');
      setSelectedProcess(null);
    } else if (currentStep === 'expert') {
      setCurrentStep('issue');
      setSelectedIssue(null);
    } else if (currentStep === 'chat') {
      setCurrentStep('expert');
      setSelectedExpert(null);
      setMessages([]);
      setSessionId(null);
    }
  }, [currentStep]);

  // 다른 전문가
  const goToNextDemo = useCallback(() => {
    if (demoStep < 3) {
      const nextStep = demoStep + 1;
      const nextExpertId = ['', 'multi-agent', 'safety', 'technical'][nextStep];
      const nextExpert = expertCategories.find(cat => cat.id === nextExpertId);
      
      if (nextExpert) {
        // 메시지만 리셋하고 전문가만 변경
        setMessages([]);
        setSessionId(null);
        handleExpertSelect(nextExpert);
      }
    }
  }, [demoStep, handleExpertSelect]);

  const restartDemo = useCallback(() => {
    resetChat();
  }, [resetChat]);

  return {
    // 기본 상태
    isOpen,
    currentStep,
    selectedProcess,
    selectedIssue,
    selectedExpert,
    sessionId,
    messages,
    inputValue,
    isLoading,
    
    // 시연 관련
    demoStep,
    apiConnected,
    lastError,
    typingEffect,
    
    // 액션 함수들
    toggleChat,
    resetChat,
    handleProcessSelect,
    handleIssueSelect,
    handleExpertSelect,
    handleSendMessage,
    handleKeyPress,
    handleInputChange,
    handleBack,
    goToNextDemo,
    restartDemo,
    
    // 데이터
    processCategories,
    processIssues,
    expertCategories,
    currentIssue: selectedIssue ? getCurrentIssue(selectedIssue.id) : null,
    
    // 상태 체크
    canProceedToNext: demoStep < 3,
    isFirstDemo: demoStep === 1,
    isLastDemo: demoStep === 3,
    
    // 스크롤 ref
    messagesEndRef
  };
};

// 헬퍼 함수들
function getQuestionText(expertId, issue) {
  const questions = {
    'multi-agent': `안녕하세요. ${issue.name} 문제에 대해 긴급히 문의드립니다. 여러 전문가의 종합적인 분석과 즉시 조치사항을 제공해주세요.`,
    'safety': `${issue.name} 상황에서 작업자 안전을 위한 개인보호장비와 안전 절차를 안내해주세요.`,
    'technical': `${issue.name} 문제의 기술적 원인 분석과 정비 매뉴얼을 제공해주세요.`
  };
  return questions[expertId] || '문제에 대해 분석해주세요.';
}

function getApiEndpoint(expertId) {
  const endpoints = {
    'multi-agent': '/chat/test',
    'safety': '/api/gpt',
    'technical': '/api/gemini'
  };
  return endpoints[expertId];
}

function getApiPayload(expertId, sessionId, message, issueId) {
  if (expertId === 'multi-agent') {
    return {
      user_message: message,
      issue_code: issueId,
      session_id: sessionId,
      user_id: "demo_user_001"
    };
  } else {
    return {
      message: message,
      session_id: sessionId
    };
  }
}

function formatResponse(response, expertId) {
  if (expertId === 'multi-agent' && response.executive_summary) {
    let text = `📋 **종합 분석 요약**\n${response.executive_summary}\n\n`;
    
    if (response.immediate_actions?.length > 0) {
      text += `🚨 **즉시 조치사항**\n`;
      response.immediate_actions.forEach((action, index) => {
        text += `${index + 1}. ${action.action} [${action.priority}]\n`;
      });
      text += '\n';
    }
    
    if (response.cost_estimation?.total) {
      text += `💰 **예상 비용**: ${response.cost_estimation.total}\n`;
    }
    
    if (response.confidence_level) {
      const percent = Math.round(response.confidence_level * 100);
      text += `🎯 **신뢰도**: ${percent}%`;
    }
    
    return text;
  }
  
  return response.response || '응답을 받았습니다.';
}